# Generated by Django 5.0.7 on 2025-03-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('contract', 'Contract'), ('evidence', 'Evidence'), ('motion', 'Motion'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
