# Generated by Django 5.0.7 on 2025-04-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_document_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
