# Generated by Django 5.0.7 on 2025-04-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_shareddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='eth_address',
            field=models.CharField(blank=True, max_length=42, unique=True),
        ),
    ]
