# Generated by Django 5.0.7 on 2025-04-24 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_eth_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='eth_address',
        ),
    ]
