# Generated by Django 5.0.7 on 2025-04-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_eth_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='eth_address',
            field=models.CharField(blank=True, max_length=42),
        ),
    ]
