# Generated by Django 5.0.7 on 2025-04-25 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_customuser_eth_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SharedDocument',
        ),
    ]
