# Generated by Django 5.0.7 on 2025-04-25 02:29

import accounts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_delete_shareddocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the document was shared.')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique token for accessing the shared document.', unique=True)),
                ('expires_at', models.DateTimeField(default=accounts.models.default_expires_at, help_text='Expiration date for the shared document link.')),
                ('document', models.ForeignKey(help_text='The document being shared.', on_delete=django.db.models.deletion.CASCADE, to='accounts.document')),
                ('owner', models.ForeignKey(help_text='The user who owns the document.', on_delete=django.db.models.deletion.CASCADE, related_name='shared_by', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(help_text='The user with whom the document is shared.', on_delete=django.db.models.deletion.CASCADE, related_name='shared_with', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shared Document',
                'verbose_name_plural': 'Shared Documents',
                'unique_together': {('document', 'owner', 'recipient')},
            },
        ),
    ]
