# Generated by Django 5.0.7 on 2025-04-25 05:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_shareddocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareddocument',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique token for accessing the shared document.'),
        ),
    ]
